version: '3.8'

services:

  redis:
    image: redis/redis-stack:latest
    container_name: hermes_redis
    ports:
      - "6379:6379"
      - "8001:8001"

  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    container_name: hermes_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=hermesmq
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
